//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursosDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURSO
    {
        public string UFCURSO { get; set; }
        public string DESCUF { get; set; }
        public string CIDADE { get; set; }
        public string CATEGCURSO { get; set; }
        public string INSTITUICAO { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public Nullable<decimal> DISTANCIA { get; set; }
        public string CURSO1 { get; set; }
        public int ID { get; set; }
        public Nullable<decimal> LATITUDE { get; set; }
        public Nullable<decimal> LONGITUDE { get; set; }
        public string ICONE { get; set; }
        public string ENDERECO { get; set; }
        public string NUMRESIDENCIA { get; set; }
        public string BAIRRO { get; set; }
        public string TELEFONE { get; set; }
        public string DETALHE { get; set; }
        public string CEP { get; set; }
        public string WEBSITE { get; set; }
        public string ATIVO { get; set; }
        public string EMAILUSUARIO { get; set; }
        public string CARGAHORARIA { get; set; }
        public string VAGAS { get; set; }
        public string DATAINICIO { get; set; }
    }
}
