//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursosDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUNICIPIO
    {
        public int CODIGO_IBGE { get; set; }
        public string NOME { get; set; }
        public float LATITUDE { get; set; }
        public float LONGITUDE { get; set; }
        public string CAPITAL { get; set; }
        public int CODIGO_UF { get; set; }
    }
}
