//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursosDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int ID { get; set; }
        public string NOME { get; set; }
        public string EMAIL { get; set; }
        public string NOMECOMPLETO { get; set; }
        public string ENDERECO { get; set; }
        public string NUMEROLOCAL { get; set; }
        public string BAIRRO { get; set; }
        public string CIDADE { get; set; }
        public string ESTADO { get; set; }
        public string PAIS { get; set; }
        public string TELEFONE { get; set; }
        public string CELULAR { get; set; }
        public string WHATSAPP { get; set; }
        public string EMAILCOMERCIAL { get; set; }
        public string WEBSITE { get; set; }
        public string UF { get; set; }
        public string CEP { get; set; }
        public Nullable<decimal> LATITUDE { get; set; }
        public Nullable<decimal> LONGITUDE { get; set; }
    }
}
